version: 2
jobs:
  test:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test

  deploy:
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - setup_remote_docker
      - checkout
      
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: ECR Login
          command: $(aws ecr get-login --no-include-email --region us-east-1)
      - run:
          name: Build overwatch docker image
          command: docker build --build-arg env=docker -t overwatch .
      - run:
          name: Tag image
          command: docker tag overwatch:latest 073174792857.dkr.ecr.us-east-1.amazonaws.com/overwatch:latest
      - run:
          name: Deploy image to ECR
          command: docker push 073174792857.dkr.ecr.us-east-1.amazonaws.com/overwatch:latest
      - run:
          name: Update overwatch service on ECS
          command: aws ecs update-service --cluster overwatch2 --service overwatch2-service --task-definition overwatch --force-new-deployment

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
